import { FormEvent, useEffect, useState } from "react";
import { Link, Navigate, NavLink, Route, Routes, useNavigate, useParams } from "react-router-dom";
import { Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import api from "./services/api";
import type { Budget, BudgetVsActualReport, Category, CategoryReport, Expense, Notification, User, YearlyReport } from "./types";

const tokenKey = "expense_tracker_token";
const money = (value: number | string) => `₹${Number(value || 0).toFixed(2)}`;
const userId = () => {
  const token = localStorage.getItem(tokenKey);
  if (!token) return 0;
  try { return Number(JSON.parse(atob(token.split(".")[1].replace(/-/g, "+").replace(/_/g, "/"))).sub); } catch { return 0; }
};

function Protected({ children }: { children: React.ReactNode }) { return localStorage.getItem(tokenKey) ? <>{children}</> : <Navigate to="/login" replace />; }
function ErrorMessage({ message }: { message: string }) { return message ? <p className="error">{message}</p> : null; }

function Layout({ children }: { children: React.ReactNode }) {
  const navigate = useNavigate();
  const links = [["/", "Overview"], ["/expenses", "Expenses"], ["/categories", "Categories"], ["/budgets", "Budgets"], ["/reports", "Reports"], ["/notifications", "Alerts"], ["/profile", "Profile"]];
  return <div className="app-shell"><aside><Link className="brand" to="/"><span>◒</span> ledgerly</Link><p className="eyebrow">YOUR MONEY, CLEARER</p><nav>{links.map(([path, label]) => <NavLink key={path} to={path} end={path === "/"}>{label}</NavLink>)}</nav><button className="logout" onClick={() => { localStorage.removeItem(tokenKey); navigate("/login"); }}>Sign out</button></aside><main><header><div><p className="eyebrow">PERSONAL FINANCE</p><h1>Good morning, keep going.</h1></div><Link className="primary-button" to="/expenses/new">+ Add expense</Link></header>{children}</main></div>;
}

function Auth({ register = false }: { register?: boolean }) {
  const navigate = useNavigate(); const [error, setError] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); const data = Object.fromEntries(new FormData(event.currentTarget)); try { if (register) await api.post("/users/register", data); const response = await api.post("/users/login", { email: data.email, password: data.password }); localStorage.setItem(tokenKey, response.data.access_token); navigate("/"); } catch (err: any) { setError(err.response?.data?.detail || "The API gateway is not reachable."); } }
  return <div className="auth-page"><div className="auth-panel"><Link className="brand" to="/"><span>◒</span> ledgerly</Link><p className="eyebrow">PERSONAL EXPENSE TRACKER</p><h1>{register ? "Start with clarity." : "Welcome back."}</h1><p className="muted">{register ? "A calmer way to understand where your money goes." : "Your financial picture, ready when you are."}</p><form onSubmit={submit}>{register && <label>Name<input name="name" required /></label>}<label>Email<input name="email" type="email" required /></label><label>Password<input name="password" type="password" minLength={8} required /></label><ErrorMessage message={error} /><button className="primary-button wide">{register ? "Create account" : "Sign in"}</button></form><p className="switch-auth">{register ? "Already have an account?" : "New to ledgerly?"} <Link to={register ? "/login" : "/register"}>{register ? "Sign in" : "Create an account"}</Link></p></div><div className="auth-art"><p className="quote">“The best financial plan is the one you can actually see.”</p><div className="art-number">₹40k<span> monthly view</span></div></div></div>;
}

function Dashboard() {
  const [expenses, setExpenses] = useState<Expense[]>([]); const [categories, setCategories] = useState<CategoryReport[]>([]); const [budget, setBudget] = useState<Budget | null>(null); const [noticeCount, setNoticeCount] = useState(0);
  useEffect(() => { Promise.allSettled([api.get("/expenses"), api.get("/reports/category"), api.get("/budgets/summary"), api.get("/notifications")]).then(([expense, category, budgets, notices]) => { if (expense.status === "fulfilled") setExpenses(expense.value.data); if (category.status === "fulfilled") setCategories(category.value.data); if (budgets.status === "fulfilled") setBudget(budgets.value.data[0] || null); if (notices.status === "fulfilled") setNoticeCount(notices.value.data.filter((item: Notification) => !item.is_read).length); }); }, []);
  const total = expenses.reduce((sum, expense) => sum + Number(expense.amount), 0);
  return <><section className="welcome"><div><p className="eyebrow">{new Date().toLocaleDateString(undefined, { month: "long", year: "numeric" }).toUpperCase()}</p><h2>Your overview</h2></div><span className="status-dot">● {noticeCount} unread alerts</span></section><section className="stats"><Stat label="Total expenses" value={money(total)} note={`${expenses.length} transactions`} /><Stat label="Monthly budget" value={money(budget?.amount || 0)} note={budget ? `${Number(budget.percentage_used).toFixed(1)}% used` : "Set your first budget"} /><Stat label="Remaining" value={money(budget?.remaining || 0)} note={budget?.status || "After expenses"} /><Stat label="Transactions" value={String(expenses.length)} note="All recorded activity" /></section><section className="dashboard-grid"><div className="card chart-card"><div className="section-heading"><div><p className="eyebrow">BREAKDOWN</p><h2>Spending by category</h2></div></div>{categories.length ? <ResponsiveContainer width="100%" height={250}><PieChart><Pie data={categories} dataKey="total_amount" nameKey="category_name" innerRadius={65} outerRadius={92} paddingAngle={3}>{categories.map((entry, index) => <Cell key={entry.category_id} fill={["#173d36", "#d7ed64", "#7ca78b", "#c9825d", "#93a6d1"][index % 5]} />)}</Pie><Tooltip formatter={(value) => money(Number(value))} /></PieChart></ResponsiveContainer> : <div className="table-empty">Add expenses to see your real category breakdown.</div>}</div><div className="card recent-card"><p className="eyebrow">LATEST</p><h2>Recent expenses</h2>{expenses.slice(0, 5).map((expense) => <div className="recent-row" key={expense.id}><span>{expense.description || "Expense"}<small>{expense.expense_date}</small></span><strong>{money(expense.amount)}</strong></div>)}{!expenses.length && <div className="table-empty">No expenses yet.</div>}</div></section></>;
}
function Stat({ label, value, note }: { label: string; value: string; note: string }) { return <article className="stat"><p>{label}</p><strong>{value}</strong><span>{note}</span></article>; }

function ExpenseForm() {
  const { id } = useParams(); const editing = Boolean(id); const navigate = useNavigate(); const [categories, setCategories] = useState<Category[]>([]); const [error, setError] = useState(""); const [initial, setInitial] = useState<Partial<Expense>>({ expense_date: new Date().toISOString().slice(0, 10), payment_method: "Card" });
  useEffect(() => { api.get("/categories").then((res) => setCategories(res.data)); if (id) api.get(`/expenses/${id}`).then((res) => setInitial(res.data)).catch(() => setError("Expense not found.")); }, [id]);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); const data = Object.fromEntries(new FormData(event.currentTarget)); try { if (editing) await api.put(`/expenses/${id}`, data); else await api.post("/expenses", data); navigate("/expenses"); } catch (err: any) { setError(err.response?.data?.detail || "Could not save expense."); } }
  return <section className="form-page"><p className="eyebrow">{editing ? "EDIT TRANSACTION" : "NEW TRANSACTION"}</p><h2>{editing ? "Edit expense" : "Add an expense"}</h2><form className="card form-grid" onSubmit={submit}><label>Amount<input name="amount" type="number" min="0.01" step="0.01" required defaultValue={initial.amount} /></label><label>Date<input name="expense_date" type="date" required defaultValue={initial.expense_date} /></label><label>Description<input name="description" required defaultValue={initial.description} placeholder="What was this for?" /></label><label>Payment method<select name="payment_method" defaultValue={initial.payment_method || "Card"}><option>Card</option><option>Cash</option><option>Bank transfer</option></select></label><label>Category<select name="category_id" required defaultValue={initial.category_id}>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><ErrorMessage message={error} /><div className="form-actions"><button type="button" onClick={() => navigate("/expenses")}>Cancel</button><button className="primary-button">Save expense</button></div></form></section>;
}
function Expenses() { const [expenses, setExpenses] = useState<Expense[]>([]); const [error, setError] = useState(""); const load = () => api.get("/expenses").then((res) => setExpenses(res.data)).catch(() => setError("Could not load expenses.")); useEffect(() => { load(); }, []); async function remove(id: number) { if (!confirm("Delete this expense?")) return; await api.delete(`/expenses/${id}`); load(); } return <section><div className="section-heading"><div><p className="eyebrow">ACTIVITY</p><h2>Expenses</h2></div><Link className="primary-button" to="/expenses/new">+ Add expense</Link></div><ErrorMessage message={error} /><div className="card table-wrap"><table><thead><tr><th>Date</th><th>Description</th><th>Category</th><th>Payment</th><th>Amount</th><th>Actions</th></tr></thead><tbody>{expenses.map((expense) => <tr key={expense.id}><td>{expense.expense_date}</td><td>{expense.description}</td><td>Category #{expense.category_id}</td><td>{expense.payment_method}</td><td>{money(expense.amount)}</td><td><Link to={`/expenses/${expense.id}/edit`}>Edit</Link> <button className="table-button" onClick={() => remove(expense.id)}>Delete</button></td></tr>)}</tbody></table>{!expenses.length && <div className="table-empty">No expenses yet.</div>}</div></section>; }

function Categories() { const [categories, setCategories] = useState<Category[]>([]); const [name, setName] = useState(""); const [error, setError] = useState(""); const load = () => api.get("/categories").then((res) => setCategories(res.data)); useEffect(() => { load(); }, []); async function add(event: FormEvent) { event.preventDefault(); try { await api.post("/categories", { name }); setName(""); load(); } catch (err: any) { setError(err.response?.data?.detail || "Could not create category."); } } async function remove(id: number) { try { await api.delete(`/categories/${id}`); load(); } catch (err: any) { setError(err.response?.data?.detail || "Category may be in use."); } } return <section><div className="section-heading"><div><p className="eyebrow">ORGANIZE</p><h2>Categories</h2></div></div><form className="inline-form" onSubmit={add}><input value={name} onChange={(e) => setName(e.target.value)} required placeholder="New category name" /><button className="primary-button">Create category</button></form><ErrorMessage message={error} /><div className="item-grid">{categories.map((category) => <article className="card item-card" key={category.id}><strong>{category.name}</strong><button className="table-button" onClick={() => remove(category.id)}>Delete</button></article>)}</div></section>; }

function Budgets() { const [budgets, setBudgets] = useState<Budget[]>([]); const [categories, setCategories] = useState<Category[]>([]); const [error, setError] = useState(""); const load = () => api.get("/budgets/summary").then((res) => setBudgets(res.data)); useEffect(() => { load(); api.get("/categories").then((res) => setCategories(res.data)); }, []); async function add(event: FormEvent<HTMLFormElement>) { event.preventDefault(); try { await api.post("/budgets", Object.fromEntries(new FormData(event.currentTarget))); event.currentTarget.reset(); load(); } catch (err: any) { setError(err.response?.data?.detail || "Could not create budget."); } } async function remove(id: number) { await api.delete(`/budgets/${id}`); load(); } return <section><div className="section-heading"><div><p className="eyebrow">PLAN AHEAD</p><h2>Budgets</h2></div></div><form className="card form-grid compact-form" onSubmit={add}><label>Amount<input name="amount" type="number" min="0.01" step="0.01" required /></label><label>Month<input name="month" type="number" min="1" max="12" defaultValue={new Date().getMonth() + 1} required /></label><label>Year<input name="year" type="number" min="2000" max="2100" defaultValue={new Date().getFullYear()} required /></label><label>Category<select name="category_id"><option value="">All categories</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><div className="form-actions"><button className="primary-button">Set budget</button></div></form><ErrorMessage message={error} /><div className="item-grid">{budgets.map((budget) => <article className="card budget-card" key={budget.id}><div><p className="eyebrow">{budget.month}/{budget.year}</p><h3>{money(budget.amount)}</h3><p>{money(budget.spent)} spent · {money(budget.remaining)} remaining</p></div><div className="budget-bar"><span style={{ width: `${Math.min(Number(budget.percentage_used), 100)}%` }} /></div><small>{Number(budget.percentage_used).toFixed(1)}% used · {budget.status}</small><button className="table-button" onClick={() => remove(budget.id)}>Delete</button></article>)}</div></section>; }

function Reports() {
  const today = new Date();
  const [categories, setCategories] = useState<CategoryReport[]>([]);
  const [budgetActual, setBudgetActual] = useState<BudgetVsActualReport[]>([]);
  const [yearly, setYearly] = useState<YearlyReport[]>([]);
  const [month, setMonth] = useState(today.getMonth() + 1);
  const [year, setYear] = useState(today.getFullYear());
  const [categoryId, setCategoryId] = useState("");
  const [availableCategories, setAvailableCategories] = useState<Category[]>([]);
  useEffect(() => { Promise.all([api.get("/reports/category"), api.get("/reports/yearly"), api.get("/categories")]).then(([category, yearData, available]) => { setCategories(category.data); setYearly(yearData.data); setAvailableCategories(available.data); }); }, []);
  useEffect(() => { const params = new URLSearchParams({ month: String(month), year: String(year) }); if (categoryId) params.set("category_id", categoryId); api.get(`/reports/budget-vs-actual?${params}`).then((response) => setBudgetActual(response.data)); }, [month, year, categoryId]);
  return <section><div className="section-heading"><div><p className="eyebrow">YOUR PATTERNS</p><h2>Reports</h2></div></div><div className="card form-grid compact-form"><label>Month<input type="number" min="1" max="12" value={month} onChange={(event) => setMonth(Number(event.target.value))} /></label><label>Year<input type="number" min="2000" max="2100" value={year} onChange={(event) => setYear(Number(event.target.value))} /></label><label>Category<select value={categoryId} onChange={(event) => setCategoryId(event.target.value)}><option value="">All budgets</option>{availableCategories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label></div><div className="dashboard-grid"><div className="card chart-card"><p className="eyebrow">MONTHLY TREND</p><h2>Spending by month</h2><ResponsiveContainer width="100%" height={280}><BarChart data={yearly}><CartesianGrid strokeDasharray="3 3" stroke="#e5e9e2" /><XAxis dataKey="month" /><YAxis /><Tooltip formatter={(value) => money(Number(value))} /><Bar dataKey="total_expenses" fill="#173d36" radius={[3, 3, 0, 0]} /></BarChart></ResponsiveContainer></div><div className="card chart-card"><p className="eyebrow">CATEGORY TOTALS</p><h2>Where money goes</h2>{categories.map((category) => <div className="report-row" key={category.category_id}><span>{category.category_name}</span><strong>{money(category.total_amount)}</strong></div>)}{!categories.length && <div className="table-empty">No report data yet.</div>}</div></div><div className="card chart-card"><p className="eyebrow">BUDGET VS ACTUAL</p><h2>{month}/{year}</h2>{budgetActual.map((report) => <div className="report-row" key={report.budget_id}><span>{report.category_name || "All categories"}<small>{report.status} · {Number(report.percentage_used).toFixed(1)}% used</small></span><strong>{money(report.actual_amount)} / {money(report.budget_amount)}</strong></div>)}{!budgetActual.length && <div className="table-empty">No budgets for this period.</div>}</div></section>;
}

function Notifications() { const [items, setItems] = useState<Notification[]>([]); const load = () => api.get("/notifications").then((res) => setItems(res.data)); useEffect(() => { load(); }, []); async function mark(id: number) { await api.put(`/notifications/${id}/read`); load(); } async function remove(id: number) { await api.delete(`/notifications/${id}`); load(); } return <section><div className="section-heading"><div><p className="eyebrow">KEEP AN EYE OUT</p><h2>Notifications</h2></div></div><div className="item-grid">{items.map((item) => <article className={`card notification ${item.is_read ? "read" : ""}`} key={item.id}><span>{item.type}</span><p>{item.message}</p><small>{new Date(item.created_at).toLocaleString()}</small><div><button className="table-button" onClick={() => mark(item.id)}>Mark read</button><button className="table-button" onClick={() => remove(item.id)}>Delete</button></div></article>)}{!items.length && <div className="card table-empty">No notifications yet.</div>}</div></section>; }

function Profile() { const [profile, setProfile] = useState<User | null>(null); const [message, setMessage] = useState(""); useEffect(() => { api.get(`/users/${userId()}`).then((res) => setProfile(res.data)); }, []); async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); await api.put(`/users/${userId()}`, data); setMessage("Profile updated."); } if (!profile) return <section className="empty-section"><h2>Loading profile...</h2></section>; return <section className="form-page"><p className="eyebrow">ACCOUNT</p><h2>Your profile</h2><form className="card form-grid" onSubmit={submit}><label>Name<input name="name" defaultValue={profile.name} required /></label><label>Email<input name="email" type="email" defaultValue={profile.email} required /></label><ErrorMessage message={message} /><div className="form-actions"><button className="primary-button">Save profile</button></div></form></section>; }

export default function App() { return <Routes><Route path="/login" element={<Auth />} /><Route path="/register" element={<Auth register />} /><Route path="*" element={<Protected><Layout><Routes><Route index element={<Dashboard />} /><Route path="expenses" element={<Expenses />} /><Route path="expenses/new" element={<ExpenseForm />} /><Route path="expenses/:id/edit" element={<ExpenseForm />} /><Route path="categories" element={<Categories />} /><Route path="budgets" element={<Budgets />} /><Route path="reports" element={<Reports />} /><Route path="notifications" element={<Notifications />} /><Route path="profile" element={<Profile />} /></Routes></Layout></Protected>} /></Routes>; }
