apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-service
  namespace: fintrack
spec:
  replicas: 1
  selector:
    matchLabels: {app: expense-service}
  template:
    metadata:
      labels: {app: expense-service}
    spec:
      containers:
        - name: expense-service
          image: fintrack/expense-service:minikube
          imagePullPolicy: IfNotPresent
          ports: [{containerPort: 8002}]
          env:
            - {name: DB_HOST, value: mysql}
            - {name: DB_PORT, value: "3306"}
            - {name: DB_NAME, value: expense_tracker}
            - name: DB_USER
              valueFrom: {secretKeyRef: {name: mysql-credentials, key: app-user}}
            - name: DB_PASSWORD
              valueFrom: {secretKeyRef: {name: mysql-credentials, key: app-password}}
            - name: JWT_SECRET
              valueFrom: {secretKeyRef: {name: mysql-credentials, key: jwt-secret}}
            - {name: BUDGET_SERVICE_URL, value: http://budget-service:8004}
            - {name: DOWNSTREAM_TIMEOUT_SECONDS, value: "2"}
          readinessProbe: {httpGet: {path: /health, port: 8002}, periodSeconds: 10}
          livenessProbe: {httpGet: {path: /health, port: 8002}, initialDelaySeconds: 20, periodSeconds: 20}
          resources: {requests: {cpu: 50m, memory: 128Mi}, limits: {cpu: 300m, memory: 256Mi}}